import itertools
import pandas as pd
from fractions import Fraction
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
import music21 as m21
from scipy.cluster.hierarchy import dendrogram

def plot_dendrogram(model, **kwargs):
    """ 
    Returns dendrogram plot from AgglomerativeClustering model
    
    Args:
        model: sklearn.cluster._agglomerative.AgglomerativeClustering, fitted

    Return:
        fig
    """
    
    # Create linkage matrix and then plot the dendrogram

    # create the counts of samples under each node
    counts = np.zeros(model.children_.shape[0])
    n_samples = len(model.labels_)
    for i, merge in enumerate(model.children_):
        current_count = 0
        for child_idx in merge:
            if child_idx < n_samples:
                current_count += 1  # leaf node
            else:
                current_count += counts[child_idx - n_samples]
        counts[i] = current_count

    linkage_matrix = np.column_stack(
        [model.children_, model.distances_, counts]
    ).astype(float)

    # Plot the corresponding dendrogram
    dendro = dendrogram(linkage_matrix, **kwargs)

    return dendro


def get_clustering_data(notes):
    """
    Returns dataframe with pitch frequency vectors for each measure 
    
    Args:
        notes: pd.DataFrame, generated by g.get_notes()

    Return:
        pd.DataFrame with rows representing a measure and the columns representing the pitch class (organized along the line of fifths), and mc (measure count), recording_year, artist info
    """

    min_tpc = notes['tpc'].min()
    max_tpc = notes['tpc'].max()
    vec_size = max_tpc - min_tpc + 1
    
    tpc_labels = [str(i) for i in range(min_tpc, max_tpc + 1)]
    # DETERMINE HOW TO SLICE SCORES 
    # Example: slicing by measure
    notes_per_measure = notes[['mc', 'tpc', 'note', 'recording_year', 'workTitle', 'artist']].groupby(['mc', 'recording_year', 'workTitle', 'artist'], as_index=False).agg(list)

    rows = []

    for _, row in notes_per_measure.iterrows():
        vec = np.zeros(vec_size)
        tpcs = row['tpc']
        tot_notes = len(tpcs)

        for tpc in tpcs:
            ind = tpc - min_tpc
            vec[ind] += 1

        vec = vec / tot_notes

        vec_dict = dict(zip(tpc_labels, vec))
        vec_dict['mc'] = row['mc']
        vec_dict['recording_year'] = row['recording_year']
        vec_dict['artist'] = row['artist']
        rows.append(vec_dict)

    return pd.DataFrame(rows)